---
- hosts: localhost
  become: true
  remote_user: root

  tasks:
    - name: Generate Secret
      ansible.builtin.shell: mix phx.gen.secret
      args:
        chdir: /var/www/blog
      register: secret_key
    - name: Export Secret
      ansible.builtin.shell: export KEY="{{secret_key.stdout}}"
      args:
        chdir: /var/www/blog
    - name: Second Task - Print the full output
      ansible.builtin.shell: "echo {{secret_key.stdout}}"
      register: output
    - name:  4th Task
      ansible.builtin.debug:
        var: output











    
