---
- hosts: localhost
  become: true
  remote_user: root

  pre_tasks: 
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: infrastructure/install_cron_job.yml
    - name: Install asdf
      ansible.builtin.git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "/Users/{{ lookup('env', 'USER') }}/.asdf"
        version: v0.13.1
    - name: Install plugins
      ansible.builtin.shell: |
        source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
        asdf plugin-add {{ item }} || exit 0
      with_items:
        - erlang
        - elixir
        - nodejs

    - name: copy project files
      copy:
        src: ./**
        dest: /var/www/blog

    # - name: install asdf

    # - name: install erlang elixir nodjs
    #   command: 
    #     cmd: asdf install







    
