---
- hosts: localhost
  become: true
  remote_user: edwin_ansible

  pre_tasks: 
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: infrastructure/packages.yml
    - name: copy project files
      copy:
        src: ./**
        dest: /var/www/blog

    # - name: install asdf

    # - name: install erlang elixir nodjs
    #   command: 
    #     cmd: asdf install







    
