- name: install cron job
  ansible.builtin.cron:
    user: root
    name: ansible provision
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/edwardcashmere/blog.git > /root/cron_logs/jobs.log"
