---
- hosts: web
  become: true
  remote_user: root
  tasks:

    - name: copy project files
      copy:
        src: /Users/dev/personal/blog/omondo_blog
        dest: /var/www/blog
        remote_src: false

    